### PR TITLE
Feature/phalcon5

### PR DESCRIPTION
**Pull request by yannux**
Here is a first PR with v5 compatibility.

- Replace Phalcon\Helper\Str
- Function params and return are typed.
- Clean use not used
- Delete mailhog messages after test so we can run again without error.

This is my first PR, hope it'll be good  or I'll made fix :)

### CODE REVIEW

**Comment by rayanlevert** [comment]
Hey, I just adapted the workflow to the latest Phalcon version and php7.4, 8.0 and 8.1 ;)

**Comment by niden** [comment]
@yannux If this is done we can merge it :)

**Comment by yannux** [comment]
@niden  I've just checked with @levertr, it's ok to merge  :)

**Comment by niden** [comment]
Thank you all! Great work

**Pull request merged**
